project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Significant Figures"
  site-url: "https://significantfigures.uk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: post01.qmd
        text: "Overrepresented compared to whom?"
      - href: post02.qmd
        text: "The role of the denominator"
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto